homeassistant:
  name: HASS @ Resin.io
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 17
  unit_system: metric
  time_zone: Europe/Brussels
  customize: !include customize.yaml
  packages: !include_dir_named packages

frontend:

http:
  api_password: !secret http_password

config:

panel_iframe:
  grafanaui:
    title: Grafana
    icon: mdi:wrench
    url: http://4303f7f4270653c54e7fecfc398dbaa5.resindevice.io/grafana/
  nodered:
    title: Node-Red
    icon: mdi:shuffle-variant
    url: http://4303f7f4270653c54e7fecfc398dbaa5.resindevice.io/red/

logger:
  default: warning
  logs:
    homeassistant.components.mqtt: debug
    homeassistant.components.automation: debug

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

updater:

# Discover some devices automatically
discovery:
  ignore:
    - apple_tv

## Philips Hue bridge config
hue:
  bridges:
    - host: 192.168.1.2
      allow_unreachable: true
      allow_hue_groups: false

remote:
  - platform: harmony
    name: Logitech Harmony
    host: !secret harmony_hub_ip
    
logbook:
map:
sun:

mqtt:
  broker: 192.168.1.162
  port: 1883

# mqtt_statestream:
#   base_topic: homeassistant
#   publish_attributes: true
#   publish_timestamps: true
#   include:
#     entities:
#       - binary_sensor.flic_80e4da720d43
#       - binary_sensor.flic_80e4da721754

camera: !include includes/cameras.yaml
history: !include includes/history.yaml
recorder: !include includes/recorder.yaml
sensor: !include includes/sensors.yaml
group: !include groups.yaml
automation: !include includes/automations.yaml
script: !include includes/scripts.yaml
shell_command: !include includes/shell_commands.yaml
input_select: !include includes/input_selects.yaml
input_boolean: !include includes/input_booleans.yaml
device_tracker: !include includes/device_trackers.yaml
ios: !include includes/ios.yaml
zone: !include includes/zones.yaml
