title: My Awesome Home
# Include external resources
resources:
  - url: /local/custom-lovelace/monster-card/monster-card.js?v=1
    type: js
  - url: /local/light-slider/light-slider.js
    type: js

# Optional background for all views. Check https://developer.mozilla.org/en-US/docs/Web/CSS/background for more examples.
background: center / cover no-repeat url("/background.png") fixed
# Exclude entities from "Unused entities" view
excluded_entities:
  - weblink.router
views:
    # Specify a tab icon if you want the view tab to be an icon.
  - id: 0  # Automatically created id
    icon: mdi:home-assistant
    # Title of the view. Will be used as the tooltip for tab icon
    title: Second view
    cards:
      - id: dc0912a79c574507a5eaa251eeb73ec2  # Automatically created id
        type: entities
        title: Light Groups
        show_header_toggle: false
        entities:
          - switch.lr_lights
          - entity: light.livingroom_lighting
            type: custom:light-slider
            switchEntity: switch.lr_lights

      - id: 877c96eadb304c128ce06ae8d3b8db4f  # Automatically created id
        type: picture-glance
        title: Living room
        aspect_ratio: 16x9
        entities:
          - entity: switch.wemo_livingroom
            icon: mdi:lamp
          - entity: light.hue_lightstrip
            icon: mdi:led-strip
          - entity: light.hue_livingroom
            icon: mdi:floor-lamp
        image: https://static-naija.akamaized.net/vllkyt3ro8mo7genvg.r900x586.255e5387.jpg
        # Entities card will take a list of entities and show their state.
      - id: 479fcdf059cd4f9fa56c4c33e328874a  # Automatically created id
        type: picture-glance
        title: Kitchen
        aspect_ratio: 16x9
        entities:
          - entity: light.fibaro_kitchen_level
            icon: mdi:ceiling-light
          - entity: light.fibaro_table_level
            icon: mdi:silverware
        image: https://www.thecarlebachshul.org/wp-content/uploads/2016/07/dinner3.jpg
        # Entities card will take a list of entities and show their state.

      - id: ac19d80b664a4f71bb8b33506c077d04  # Automatically created id
        type: picture-entity
        image: https://www.ikea.com/gb/en/images/range-introduction/ikea-malm-desk__1364493552121-s3.jpg
        aspect_ratio: 16x9
        show_state: true
        entity: light.hue_desk
        tap_action: toggle

      - id: 451732ca62ff4450abd346629dcd196f  # Automatically created id
        type: entities
        # Title of the entities card
        title: ' '
        show_header_toggle: false
        # The entities here will be shown in the same order as specified.
        # Each entry is an entity ID or a map with extra options.
        entities:
          - light.hue_livingroom
          - light.hue_lightstrip
          - light.hue_desk
          - light.fibaro_table_level
          - light.fibaro_kitchen_level
          # - entity: light.hue_livingroom
          #   # Override the name to use
          #   name: LR Lights

        # The markdown card will render markdown text.
      # - type: markdown
      #   title: Lovelace
      #   content: >
      #     Welcome to your **Lovelace UI**.
    # View tab title.
  - icon: mdi:chart-areaspline
    title: Stats
    # Optional unique id for direct access /lovelace/${id}
    id: example
    cards:
        # The filter card will filter entities for their state
      - id: 46e68c93b8e54ae5a19401365ce64558  # Automatically created id
        type: iframe
        url: https://dglerum.noip.me/grafana/d/lxB8GikRk/our-home?orgId=1&panelId=11&fullscreen&kiosk
        aspect_ratio: 75%

      - id: f73f892b5d494d57a6600f77effcd648  # Automatically created id
        type: iframe
        url: https://dglerum.noip.me/grafana/d/lxB8GikRk/our-home?orgId=1&panelId=8&fullscreen&kiosk
        aspect_ratio: 75%

      - id: b45b37b0476e4ea4849b6c82a70781e7  # Automatically created id
        type: iframe
        url: https://dglerum.noip.me/grafana/d/lxB8GikRk/our-home?orgId=1&panelId=9&fullscreen&kiosk
        aspect_ratio: 75%
