#################################################################
## Packages / Weather
#################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    sensor.solar_angle:
      unit_of_measurement: "°"
      icon: mdi:triangle-outline
    sensor.yr_symbol:
      friendly_name: " "
    sensor.yr_fog:
      friendly_name: "Fog"
    sensor.dark_sky_hourly_summary:
      friendly_name: "Current:"
    sensor.dark_sky_daily_summary:
      friendly_name: "Forecast:"
    sensor.pws_temp_c:
      friendly_name: "Outdoor Temp"
    sensor.cpu_temperature:
      friendly_name: "CPU Temp"
    sensor.dark_sky_daily_high_temperature:
      friendly_name: "High"
    sensor.dark_sky_daily_high_temperature_1:
      friendly_name: "Forecast High"
    sensor.dark_sky_daily_low_temperature:
      friendly_name: "Low"
    sensor.dark_sky_daily_low_temperature_1:
      friendly_name: "Forecast Low"
    sensor.dark_sky_precip_probability:
      friendly_name: "Rain"
    sensor.dark_sky_precip_probability_1:
      friendly_name: "Forecast Rain"
    sensor.dark_sky_cloud_coverage:
      friendly_name: "Cloud"
    sensor.dark_sky_wind_speed:
      friendly_name: "Wind"
    sensor.dark_sky_wind_bearing:
      friendly_name: "Wind Bearing"
    sensor.dark_sky_cloud_coverage_1:
      friendly_name: "Forecast Cloud"

################################################
## Group
################################################

group:
  sun:
    name: Sun
    view: no
    entities:
      - sun.sun
      - sensor.moon

  # weather overview:
  #   name: Weather Overview
  #   view: no
  #   entities:
  #     - sensor.pws_temp_c
  #     - sensor.pws_relative_humidity
  #     - sensor.pws_precip_1d
  #     - sensor.pws_wind_kph
  #     - sensor.pws_alerts
  #
  # daily forcast:
  #   name: Daily Forcast
  #   view: no
  #   entities:
  #     - sensor.pws_temp_high_1d_c
  #     - sensor.pws_temp_high_2d_c
  #     - sensor.pws_temp_high_3d_c
  #     - sensor.pws_temp_high_4d_c

################################################
## Sensor
################################################
binary_sensor:
  - platform: iss

sensor:
  - platform: moon

## Weather Sensors Weatherunderground
  # - platform: wunderground
  #   api_key: !secret wunderground_api
  #   pwd_id: !secret wunderground_pws_id
  #   scan_interval: 180
  #   monitored_conditions:
  #     - relative_humidity
  #     - pressure_mb
  #     - temp_high_1d_c
  #     - temp_c
  #     - temp_low_1d_c
  #     - precip_1d
  #     - precip_1d_mm
  #     - precip_today_string
  #     - wind_kph
  #     - wind_1d_kph
  #     - wind_dir
  #     - feelslike_c
  #     - alerts
  #     - temp_high_2d_c
  #     - temp_high_3d_c
  #     - temp_high_4d_c
  #     - weather_1d_metric
  #     - weather_2d_metric
  #     - weather_3d_metric
  #     - weather_4d_metric

################################################
## Weather
################################################

## Weather Dark Sky
  - platform: darksky
    api_key: !secret darksky_api_key
    forecast:
      - 1
      - 2
      - 3
      - 4
      - 5
    monitored_conditions:
      - icon
      - summary
      - nearest_storm_distance
      - nearest_storm_bearing
      - humidity
      - temperature
      - temperature_high
      - temperature_low
      - apparent_temperature
      - apparent_temperature_high
      - apparent_temperature_low
      - wind_speed
      - wind_bearing
      - precip_type
      - precip_probability
      - precip_accumulation
      - precip_intensity
      - precip_intensity_max
      - uv_index
      - daily_summary
      - pressure
      - visibility
    scan_interval:
      minutes: 5

################################################
## Sun
################################################

sun:
