homeassistant:
  customize:
    binary_sensor.hallway_motion:
      friendly_name: Hallway
    binary_sensor.toilet_downstairs_motion:
      friendly_name: Toilet Downstairs
    binary_sensor.toilet_upstairs_motion:
      friendly_name: Toilet Upstairs

group:
  hue_motion_sensors:
    name: Motion Sensors
    icon: mdi:motion
    view: no
    entities:
      - binary_sensor.hallway_motion
      - binary_sensor.toilet_upstairs_motion
      - binary_sensor.toilet_downstairs_motion

binary_sensor:
  - platform: mqtt
    name: Hallway Motion
    state_topic: "hass/binary_sensor/hallway_motion"
    payload_on: "true"
    payload_off: "false"

  - platform: mqtt
    name: Toilet Downstairs Motion
    state_topic: "hass/binary_sensor/toilet_downstairs_motion"
    payload_on: "true"
    payload_off: "false"

  - platform: mqtt
    name: Toilet Upstairs Motion
    state_topic: "hass/binary_sensor/toilet_upstairs_motion"
    payload_on: "true"
    payload_off: "false"

# automation:
#   - alias: Motion Detected
#     trigger:
#       platform: state
#       entity_id: binary_sensor.hallway_motion, binary_sensor.wc_downstairs_motion, binary_sensor.wc_upstairs_motion
#       to: 'on'
#     action:
#       - service: notify.pushover
#         data_template:
#           message: >
#             '{{ trigger.to_state.attributes.friendly_name }} motion detected!'
#           data:
#             url: https://dglerum.noip.me
