# ring:
#   username: !secret ring_username
#   password: !secret ring_password
automation:
  - alias: 'Doorbell Motion'
    initial_state: 'off'
    trigger:
      - platform: state
        entity_id: binary_sensor.ring_front_door_motion
        from: 'off'
        to: 'on'
    action:
      - delay: '00:05:00'
      - service: downloader.download_file
        data_template:
          url: "{{ states.camera.front_door.attributes.video_url }}"
          filename: "last.mpg"
          overwrite: true

binary_sensor:
  - platform: ring

# camera:
#   - platform: ring

sensor:
  - platform: ring

  - platform: template
    sensors:
      last_motion:
        entity_id:
          - sensor.ring_front_door_last_motion
        value_template: >-
          {% if states.sensor.ring_front_door_last_motion.attributes.created_at %}
           {% set today = now().day | int %}
           {% set motion_date = (((as_timestamp(states.sensor.ring_front_door_last_motion.attributes.created_at)) | timestamp_custom("%d")) | int) %}
           {% if today == motion_date %}
             {% set day = "Today" %}
           {% elif today == 1 and motion_date > 27 %}
             {% set day = "Yesterday" %}
           {% elif (today - 1) == motion_date %}
             {% set day = "Yesterday" %}
           {% else %}
             {% set day = as_timestamp(states.sensor.ring_front_door_last_motion.attributes.created_at) | timestamp_custom("%A")%}
           {% endif %}
           {% set time = as_timestamp(states.sensor.ring_front_door_last_motion.attributes.created_at) | timestamp_custom("%l:%M %p")%}
           {{[day,time]|join(" at ")}}
          {% else %} Oops
          {% endif %}
      last_ring:
        entity_id:
          - sensor.ring_front_door_last_ding
        value_template: >-
          {% if states.sensor.ring_front_door_last_ding.attributes.created_at %}
           {% set today = now().day | int %}
           {% set ring_date = (((as_timestamp(states.sensor.ring_front_door_last_ding.attributes.created_at)) | timestamp_custom("%d")) | int) %}
           {% if today == ring_date %}
             {% set day = "Today" %}
           {% elif today == 1 and ring_date > 27 %}
             {% set day = "Yesterday" %}
           {% elif (today - 1) == ring_date %}
             {% set day = "Yesterday" %}
           {% else %}
             {% set day = as_timestamp(states.sensor.ring_front_door_last_ding.attributes.created_at) | timestamp_custom("%A")%}
           {% endif %}
           {% set time = as_timestamp(states.sensor.ring_front_door_last_ding.attributes.created_at) | timestamp_custom("%l:%M %p")%}
           {{[day,time]|join(" at ")}}
          {% else %} Oops
          {% endif %}
