#################################################################
## Packages / Presence
#################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    device_tracker.glerums_iphone:
      friendly_name: 'Davy iOS'
    device_tracker.iphone_van_isabel:
      friendly_name: 'Isabel'
    sensor.glerums_iphone_x_battery_level:
      friendly_name: "Battery iPhone X"
    sensor.iphone_van_isabel_battery_level:
      friendly_name: "Battery iPhone 6"
    device_tracker.davy_bayesian:
      friendly_name: 'Davy'
    device_tracker.davy_owntracks:
      friendly_name: "Davy Owntracks"
    device_tracker.davy_nodered:
      friendly_name: "Davy Node Red"
    device_tracker.davy_homekit:
      friendly_name: "Davy Homekit"
    device_tracker.davy_ping:
      friendly_name: "Davy Ping"
    sensor.davy_google:
      friendly_name: "Davy Geocode"

################################################
## Group
################################################

group:
  people:
    name: People
    view: no
    entities:
      - sensor.davy_google
      - device_tracker.glerums_iphone
      - device_tracker.davy_bayesian
      - device_tracker.davy_nodered
      - device_tracker.davy_homekit
      - device_tracker.davy_ping
      # - device_tracker.davy_owntracks
      - device_tracker.iphone_van_isabel
      - sensor.glerums_iphone_x_battery_level
      - sensor.iphone_van_isabel_battery_level
#       - sensor.commute_to_work
#       - sensor.commute_from_work
#       - sensor.james_to_home
#
#   family:
#     name: Family
#     view: no
#     entities:
#       - sensor.james
#       - sensor.tina
#
#   ble_tracker_james:
#     name: BLE Tracker James
#     view: no
#     entities:
#       - sensor.ble_james_downstairs
#       - sensor.ble_james_upstairs
#       - sensor.ble_james_patio
#
#   ble_tracker_tina:
#     name: BLE Tracker Tina
#     view: no
#     entities:
#       - sensor.ble_tina_downstairs
#       - sensor.ble_tina_upstairs
#       - sensor.ble_tina_patio

################################################
## Sensor
################################################

sensor:

- platform: google_geocode
  scan_interval: 60
  name: Davy Google
  origin: device_tracker.glerums_iphone
  options: street_number, street, city
  display_zone: hide
  gravatar: dglerum@gmail.com
  api_key: !secret geocode_api

################################################
## Input Boolean
################################################

input_boolean:
  davy_homekit_present:
    name: Davy HomeKit
    icon: mdi:account
  isabel_homekit_present:
    name: Isabel Homekit
    icon: mdi:account

################################################
## Binary Sensor
################################################

binary_sensor:
  - platform: bayesian
    prior: 0.5
    name: 'Davy Presence'
    probability_threshold: 0.9
    observations:
      - entity_id: 'device_tracker.davy_ping'
        prob_given_true: 0.9
        prob_given_false: 0.1
        platform: 'state'
        to_state: 'home'
      - entity_id: 'device_tracker.glerums_iphone'
        prob_given_true: 0.9
        prob_given_false: 0.2
        platform: 'state'
        to_state: 'home'
      - entity_id: 'device_tracker.davy_owntracks'
        prob_given_true: 0.9
        prob_given_false: 0.4
        platform: 'state'
        to_state: 'home'
      - entity_id: 'device_tracker.davy_homekit'
        prob_given_true: 0.9
        prob_given_false: 0.2
        platform: 'state'
        to_state: 'home'
      - entity_id: 'device_tracker.davy_nodered'
        prob_given_true: 0.8
        prob_given_false: 0.2
        platform: 'state'
        to_state: 'home'
      - entity_id: 'device_tracker.tile_glerums_iphone_x'
        prob_given_true: 0.8
        prob_given_false: 0.4
        platform: 'state'
        to_state: 'home'

################################################
## Device Tracker
################################################

device_tracker:
  - platform: ping
    hosts:
      davy_ping: !secret davy_ping
      isabel_ping: 192.168.1.8
  # - platform: owntracks
  #   max_gps_accuracy: 200

  # - platform: bluetooth_tracker
  #   request_rssi: true
