#################################################################
#                           Customize                           #
#################################################################

homeassistant:
  customize:
    input_boolean.light_automation:
      friendly_name: Sunlight Automation
    light.fibaro_kitchen_level:
      friendly_name: "Kitchen"
    light.fibaro_table_level:
      friendly_name: "Table"
    light.fibaro_hallway_level:
      friendly_name: "Hallway"
    light.fibaro_stair_level:
      friendly_name: "Stair"
    sensor.fibaro_hallway_power:
      friendly_name: "Hallway Use"
    sensor.fibaro_kitchen_power:
      friendly_name: "Kitchen Use"
    sensor.fibaro_stair_power:
      friendly_name: "Stair Use"
    sensor.fibaro_table_power:
      friendly_name: "Table Use"
    light.hue_lightstrip:
      friendly_name: "LED Strip"
    light.hue_livingroom:
      friendly_name: "Floorlamp"
    light.hue_desk:
      friendly_name: "Desk"


# sensor:
#   - platform: template
#     sensors:
#       fibaro_kitchen_power:
#         friendly_name: "Fibaro Kitchen Power"
#         unit_of_measurement: 'degrees'
#         value_template: "{{ state_attr('light.fibaro_kitchen_level', 'power_consumption') }}"


#################################################################
#                          Input Booleans                       #
#################################################################

input_boolean:
  light_automation:
    initial: on
    name: Light Automation
    icon: mdi:light

#################################################################
#                          Groups                               #
#################################################################

group:
  lights:
    name: Lights
    view: no
    control: hidden
    entities:
      - light.hue_desk
      - light.hue_lightstrip
      - light.hue_livingroom
      - light.tv_lights
      - light.fibaro_kitchen_level
      - light.fibaro_table_level
      - light.kitchen_lighting
      - light.livingroom_lighting
      - input_boolean.light_automation

  light_groups:
    name: Light Groups
    view: no
    control: hidden
    entities:
      - light.kitchen_lighting
      - light.livingroom_lighting

  lr_lights:
    view: no
    control: hidden
    entities:
      - light.hue_desk
      - light.hue_lightstrip
      - light.hue_livingroom
      - switch.television_lights

#################################################################
#                          Light Groups                         #
#################################################################

light:
  - platform: group
    name: Kitchen Lighting
    entities:
      - light.fibaro_kitchen_level
      - light.fibaro_table_level

  - platform: group
    name: Livingroom Lighting
    entities:
      - light.hue_desk
      - light.hue_lightstrip
      - light.hue_livingroom

  - platform: template
    lights:
      tv_lights:
        friendly_name: "TV Lights"
        value_template: >-
            {% if is_state('switch.television_lights', 'on') %}
              on
            {% else %}
              off
            {% endif %}
        turn_on:
          - service: switch.turn_on
            entity_id: switch.television_lights
        turn_off:
          - service: switch.turn_off
            entity_id: switch.television_lights

#################################################################
#                          Automations                          #
#################################################################

automation:
  - alias: Downstairs Sunlight
    initial_state: 'on'
    condition:
    # Run only when light automation boolean is active
      - condition: state
        entity_id: input_boolean.light_automation
        state: 'on'
    # Run hourly
    trigger:
      - platform: time
        minutes: 00
        seconds: 00
    action:
      - service: script.livingroom_lights_dim
      - service: script.kitchen_lights_dim
      - service: script.table_lights_dim

#################################################################
#                          Scripts                              #
#################################################################

script:
  # Master script for ALL LIGHTS OFF
  # Turns off all with clean up for milight
  # Also turns off additional items via-sub scripts
  #  * group.tracked_users = not_home
  #    * turn off Alexa, bathroom fan, bandwidth throttling
  #  * roku = playing
  #    * turn off grow light, aquarium, bathroom_fan
  # kitchen_lighting:
  #   alias: Kitchen Lighting
  #   sequence:
  #     - service_template: >
  #         light.turn_{{ desire }}
  #       entity_id: light.fibaro_kitchen_level, light.fibaro_table_level
  downstairs_sunrise:
    alias: Downstairs Sunrise
    sequence:

      # Turn the lights to low brightness at a very warm temperature
      - service: light.turn_on
        data:
          entity_id: group.lights_bedroom
          transition: 60
          brightness: 51
          kelvin: 2700

      # Wait 5 seconds
      - delay: 00:00:05

      # Over ten minutes, turn the lights a little brighter and to a
      # cooler-than-soft-white color.
      - service: light.turn_on
        data:
          entity_id: group.lights_bedroom
          transition: 600
          brightness: 63
          kelvin: 3600

      # Wait again
      - delay: 00:00:05

      # Finally, over fifteen minutes, shift the lights to a cool white at 90%.
      - service: light.turn_on
        data:
          entity_id: group.lights_bedroom
          transition: 900
          brightness: 230
          kelvin: 4200

  kitchen_lights_dim:
    alias: Kitchen Lights Dim
    sequence:
      - condition: state
        entity_id: 'switch.kitchen_lights'
        state: 'on'
      - service: scene.turn_on
        data_template:
          entity_id: >
            scene.kitchen_
            {%- if now().hour < 7 %}night
            {% elif now().hour < 18 %}daylight
            {% elif now().hour < 21 %}evening
            {% elif now().hour >= 21 %}night
            {% endif %}

  table_lights_dim:
    alias: Table Lights Dim
    sequence:
      - condition: state
        entity_id: 'switch.table_lights'
        state: 'on'
      - service: scene.turn_on
        data_template:
          entity_id: >
            scene.table_
            {%- if now().hour < 7 %}night
            {% elif now().hour < 18 %}daylight
            {% elif now().hour < 21 %}evening
            {% elif now().hour >= 21 %}night
            {% endif %}

  livingroom_lights_dim:
    alias: Downstairs Lights Dim
    sequence:
      - condition: state
        entity_id: 'switch.livingroom_lights'
        state: 'on'
      - service: scene.turn_on
        data_template:
          entity_id: >
            scene.livingroom_
            {%- if now().hour < 7 %}night
            {% elif now().hour < 18 %}daylight
            {% elif now().hour < 21 %}evening
            {% elif now().hour >= 21 %}night
            {% endif %}

  kitchen_lights_on:
    alias: Kitchen Lights On
    sequence:
      - service: scene.turn_on
        data_template:
          entity_id: >
            scene.kitchen_
            {%- if now().hour < 7 %}night
            {% elif now().hour < 18 %}daylight
            {% elif now().hour < 21 %}evening
            {% elif now().hour >= 21 %}night
            {% endif %}

  table_lights_on:
    alias: Table Lights On
    sequence:
      - service: scene.turn_on
        data_template:
          entity_id: >
            scene.table_
            {%- if now().hour < 7 %}night
            {% elif now().hour < 18 %}daylight
            {% elif now().hour < 21 %}evening
            {% elif now().hour >= 21 %}night
            {% endif %}

  dinner_lights_on:
    alias: Dinner Lights On
    sequence:
      - service: scene.turn_on
        data_template:
          entity_id: >
            scene.dinner_
            {%- if now().hour < 7 %}night
            {% elif now().hour < 18 %}daylight
            {% elif now().hour < 21 %}evening
            {% elif now().hour >= 21 %}night
            {% endif %}

  livingroom_lights_on:
    alias: Livingroom Lights On
    sequence:
      - service: scene.turn_on
        data_template:
          entity_id: >
            scene.livingroom_
            {%- if now().hour < 7 %}night
            {% elif now().hour < 18 %}daylight
            {% elif now().hour < 21 %}evening
            {% elif now().hour >= 21 %}night
            {% endif %}
