#################################################################
## Packages / Hue Motion
#################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    binary_sensor.hallway_motion:
      friendly_name: Hallway
    inary_sensor.motion_wc2:
      friendly_name: Toilet Downstairs
    inary_sensor.motion_wc1:
      friendly_name: Toilet Upstairs
    binary_sensor.kitchen_motion:
      friendly_name: Kitchen
    binary_sensor.hue_motion:
      friendly_name: Philips HUE
    input_boolean.homekit_motion:
      friendly_name: Homekit Motion

################################################
## Group
################################################

group:
  hue_motion_sensors:
    name: Motion
    icon: mdi:motion
    view: no
    entities:
      - binary_sensor.motion_hallway
      - inary_sensor.motion_wc1
      - inary_sensor.motion_wc2
      - binary_sensor.motion_kitchen
      - binary_sensor.motion_tester
      - input_boolean.homekit_motion

################################################
## Binary Sensor
################################################

# binary_sensor:
#   - platform: mqtt
#     name: Hallway Motion
#     state_topic: "hass/binary_sensor/hallway_motion"
#     payload_on: "true"
#     payload_off: "false"
#
#   - platform: mqtt
#     name: Toilet Downstairs Motion
#     state_topic: "hass/binary_sensor/toilet_downstairs_motion"
#     payload_on: "true"
#     payload_off: "false"
#
#   - platform: mqtt
#     name: Toilet Upstairs Motion
#     state_topic: "hass/binary_sensor/toilet_upstairs_motion"
#     payload_on: "true"
#     payload_off: "false"
#
#   - platform: mqtt
#     name: Kitchen Motion
#     state_topic: "hass/binary_sensor/kitchen_motion"
#     payload_on: "true"
#     payload_off: "false"
#
#   - platform: mqtt
#     name: HUE Motion
#     state_topic: "hass/binary_sensor/hue_motion"
#     payload_on: "true"
#     payload_off: "false"

################################################
## Automation
################################################

# automation:
#   - alias: Motion Detected
#     trigger:
#       platform: state
#       entity_id: binary_sensor.hallway_motion, binary_sensor.wc_downstairs_motion, binary_sensor.wc_upstairs_motion
#       to: 'on'
#     action:
#       - service: notify.pushover
#         data_template:
#           message: >
#             '{{ trigger.to_state.attributes.friendly_name }} motion detected!'
#           data:
#             url: https://dglerum.noip.me
