sensor:
  platform: feedparser
  name: Engineering Feed
  feed_url: 'https://www.sciencedaily.com/rss/matter_energy/engineering.xml'
  date_format: '%a, %b %d %I:%M %p'
  inclusions:
    - title
    - link
    - description
    - image
    - language
    - pubDate
  exclusions:
    - language
