#################################################################
## Packages / Tile
#################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    device_tracker.tile_pe5a33af6aed78690191414301c2946ef:
      friendly_name: iPhone X
      icon: mdi:radar
    device_tracker.tile_1da6142fd8f65ae3:
      friendly_name: Laptop Bag
      icon: mdi:radar
    device_tracker.tile_1e2b8c38e30fbb4d:
      friendly_name: Tesla Model S
      icon: mdi:radar
    device_tracker.tile_92ed8033933bc67b:
      friendly_name: Work Keys
      icon: mdi:radar

################################################
## Group
################################################

group:
  tile:
    name: Tile Trackers
    view: no
    control: hidden
    entities:
      - device_tracker.tile_pe5a33af6aed78690191414301c2946ef
      - device_tracker.tile_1da6142fd8f65ae3
      - device_tracker.tile_1e2b8c38e30fbb4d
      - device_tracker.tile_92ed8033933bc67b
