#################################################################
## Packages / Speech
#################################################################

################################################
## Group
################################################

group:
  speech_engine:
    name: Speech Engine
    control: hidden
    entities:
      - input_boolean.guest_mode
      - input_boolean.alert_mode
      - input_boolean.speech_notifications
      - automation.people_greeting
      - input_boolean.last_message
      - input_boolean.home_stats
      - input_boolean.greeting_davy
      # - script.voice_notify
      # - script.speech_engine

################################################
## Automation
################################################

automation:
######################################################################
##  Announce when people come or go.
## Announce over all Chromecast Audios
######################################################################
  - alias: 'People Greeting'
    initial_state: 'off'
    trigger:
      # - platform: state
      #   entity_id:
      #     - device_tracker.davy_bayesian
      #   from: 'not_home'
      #   to: 'home'
      #   for: '00:02:00'

      - platform: state
        entity_id: input_boolean.greeting_davy
        to: 'on'
        from: 'off'

    action:
      - service: script.speech_engine
        data_template:
          personarriving: >
            {% set person = trigger.entity_id.split('.')[1]|replace('_', ' ')%}
            {%- macro greeting_sentence(person) -%}
            {{ [
            "Welcome back home " ~ person,
            "Guess who is home?" ~ person +" is!",
            person + " is now in the house.",
            "Welcome Home " ~ person + ".  We have missed you. Or at least Molly did.",
            "Our home is now complete, Rest your head and relax your feet! Welcome Back " ~ person,
            "Life is like a song, you’re back where you belong. Welcome home " ~ person,
            "Hey there " ~ person + " Welcome Home!",
            "Knock Knock. Who is There? "   ~ person +" is!",
            "The garage door opener just told me that "   ~ person +" is home.",
            person + " can not hide from the system. Welcome home.",
            person ~ "! You are home!",
            "I know a secret! "  ~ person +" is home!",
            "Hey "  ~ person +". Your arrival has been recorded by the Smartest house on the block.",
            "Take note Molly! "  ~ person +" is home.",
            "I am sensing a disturbance in the force. "  ~ person +" must be home!",
            "And the house becomes a home. Welcome back " ~ person,
            person + " is now here.  Hash tag Welcome Home.",
            person + " is now here.  Hash tag Home.",
            person + " is now here.  Hash tag Smart Home.",
            "Just a quick announcement. " ~ person +" has arrived!",
            "Pardon the interruption but " ~ person +" is home!",
            "My systems are picking up the presence of additional humans. " ~ person +" has been identified as home."
            ] | random }}
            {%- endmacro -%}
            {{greeting_sentence(person)}}
          call_responsibilities: 1
          call_no_announcement: 1
          call_garage_check: 1
          call_window_check: 1

######################################################################
##  Some home facts when we get back home from being away.
######################################################################
  - alias: 'Home Stats'
    initial_state: 'on'
    trigger:
      # - platform: state
      #   entity_id:
      #     - sensor.davy
      #   from: 'not_home'
      #   to: 'home'
      #   for: '00:03:00'

      - platform: state
        entity_id: input_boolean.home_stats
        to: 'on'
        from: 'off'

    action:

      # - wait_template: >-
      #    {{ is_state('group.garage_doors', 'closed') }}
      #   timeout: 00:05:30

      - service: script.speech_engine
        data:
          # call_dark_outside: 1
          call_inside_weather: 1
          call_responsibilities: 1
          call_outside_weather: 1
          call_garage_check: 1
          call_window_check: 1
          call_light_check: 1

################################################
## Script
################################################

script:
  voice_notify:
    sequence:
    - condition: and
      conditions:
        - condition: or
          conditions:
            - condition: state
              entity_id: group.family
              state: 'on'
            - condition: state
              entity_id: input_boolean.guest_mode
              state: 'on'
        - condition: or
          conditions:
            - condition: time
              after: '09:00:00'
              before: '22:00:00'
            - condition: state
              entity_id: input_boolean.alert_mode
              state: 'on'
    #     - condition: or
    #       conditions:
    #         - condition: template
    #           value_template: >
    #             {% if is_state('media_player.livingroom', 'playing') %}
    #             false
    #             {% else %}
    #             true
    #             {% endif %}
    #         - condition: state
    #           entity_id: input_boolean.alert_mode
    #           state: 'on'
        # - condition: state
        #   entity_id: input_boolean.speech_notifications
        #   state: 'on'
    # - service: switch.turn_on
    #   entity_id: switch.living_room_amp
    # - delay: '00:00:05'

    # - service: media_player.turn_on
    #   entity_id: media_player.livingroom

    # - service: media_player.volume_set
    #   entity_id:
    #     - media_player.apple_tv
    #   data_template:
    #     volume_level: >
    #       {% if now().strftime("%H")|int < 12 and now().strftime("%H")|int > 6%}
    #       0.25
    #       {% elif now().strftime("%H")|int > 12 and now().strftime("%H")|int < 20%}
    #       0.45
    #       {% else %}
    #       0.20
    #       {% endif %}

    - service: mqtt.publish
      data_template:
        payload: '{{ value1 }}'
        topic: 'polly/lastmsg'
        retain: true

    # - service: tts.amazon_polly_say
    #   entity_id: media_player.livingroom
    #   data_template:
    #     message: >
    #       {% if now().strftime("%H")|int < 12 and now().strftime("%H")|int > 6%}
    #       "Good morning.
    #       {% elif now().strftime("%H")|int > 12 and now().strftime("%H")|int < 17%}
    #       "Good afternoon.
    #       {% else %}
    #       "Good evening.
    #       {% endif %}
    #       {{ value1 }}"
    #     cache: true

    # - service: media_player.alexa_tts
    #   entity_id: media_player.davys_echo_dot
    #   data_template:
    #     message: >
    #       {% if now().strftime("%H")|int < 12 and now().strftime("%H")|int > 6%}
    #       "Good morning.
    #       {% elif now().strftime("%H")|int > 12 and now().strftime("%H")|int < 17%}
    #       "Good afternoon.
    #       {% else %}
    #       "Good evening.
    #       {% endif %}
    #       {{ value1 }}"

    - service: input_boolean.turn_off
      entity_id:
        - input_boolean.last_message
        - input_boolean.alert_mode
