homeassistant:
  customize:
    binary_sensor.flic_80e4da720d43:
      friendly_name: black
    binary_sensor.flic_80e4da721754:
      friendly_name: white

group:
  flic:
    name: Flic Buttons
    view: no
    entities:
      - binary_sensor.flic_80e4da720d43
      - binary_sensor.flic_80e4da721754

binary_sensor:
  - platform: flic

automation:
  - action:
    - service: mqtt.publish
      data_template:
        topic: "flic/{{ trigger.entity_id.attributes.friendly_name }}"
        payload: "{{ trigger.event.data.click_type }}"
    alias: Black Flic - Single
    trigger:
    - platform: event
      event_type: flic_click
      event_data:
        button_name: flic_80e4da720d43
        click_type: single

  - action:
    - service: mqtt.publish
      data:
        topic: flic/black
        payload: "double"
    alias: Black Flic - Double
    trigger:
    - platform: event
      event_type: flic_click
      event_data:
        button_name: flic_80e4da720d43
        click_type: double

  - action:
    - service: mqtt.publish
      data:
        topic: flic/black
        payload: "hold"
    alias: Black Flic - Hold
    trigger:
    - platform: event
      event_type: flic_click
      event_data:
        button_name: flic_80e4da720d43
        click_type: hold

  - action:
    - service: mqtt.publish
      data:
        topic: flic/white
        payload: "single"
    alias: White Flic - Single
    trigger:
    - platform: event
      event_type: flic_click
      event_data:
        button_name: flic_80e4da721754
        click_type: single

  - action:
    - service: mqtt.publish
      data:
        topic: flic/white
        payload: "double"
    alias: White Flic - Double
    trigger:
    - platform: event
      event_type: flic_click
      event_data:
        button_name: flic_80e4da721754
        click_type: double

  - action:
    - service: mqtt.publish
      data:
        topic: flic/white
        payload: "hold"
    alias: White Flic - Hold
    trigger:
    - platform: event
      event_type: flic_click
      event_data:
        button_name: flic_80e4da721754
        click_type: hold
