binary_sensor:
  - platform: flic

automation:
  - action:
    - service: mqtt.publish
      data:
        topic: flic/black
        payload: "single"
    alias: Black Flic - Single
    trigger:
    - platform: event
      event_type: flic_click
      event_data:
        button_name: flic_80e4da720d43
        click_type: single

  - action:
    - service: mqtt.publish
      data:
        topic: flic/black
        payload: "double"
    alias: Black Flic - Double
    trigger:
    - platform: event
      event_type: flic_click
      event_data:
        button_name: flic_80e4da720d43
        click_type: double

  - action:
    - service: mqtt.publish
      data:
        topic: flic/black
        payload: "hold"
    alias: Black Flic - Hold
    trigger:
    - platform: event
      event_type: flic_click
      event_data:
        button_name: flic_80e4da720d43
        click_type: hold
    
