#################################################################
#                                                               #
#                      Packages/Git   OK                        #
#                                                               #
#################################################################

#################################################################
#                           Input Selects                       #
#################################################################

input_select:
  git_branch:
    name: GIT Branch
    options:
      - select branch
      - dev
      - master
    initial: select branch

#################################################################
#                           Automations                         #
#################################################################

automation:
  - action:
    - service: shell_command.checkout_dev_branch_from_github
      data:
        branch: "{{ trigger.to_state.state }}"
    - service: shell_command.update_new_commits_sensor
      data:
        api_password: !secret http_password
    alias: Checkout GIT Dev Branch
    trigger:
    - platform: state
      entity_id: input_select.git_branch
      to: dev

  - action:
    - service: shell_command.checkout_master_branch_from_github
      data:
        branch: "{{ trigger.to_state.state }}"
    - service: shell_command.update_new_commits_sensor
      data:
        api_password: !secret http_password
    alias: Checkout GIT Master Branch
    trigger:
    - platform: state
      entity_id: input_select.git_branch
      to: master

  - action:
    - service: shell_command.update_new_commits_sensor
      data:
        api_password: !secret http_password
    alias: 'Get Branch and Commits info'
    trigger:
      platform: homeassistant
      event: start
