- alias: Log Level
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_select.log_level
  action:
    - service: logger.set_level
      data_template:
        homeassistant.components: "{{ trigger.to_state.state }}"

- alias: 'Start HomeKit'
  initial_state: 'on'
  trigger:
    - platform: homeassistant
      event: start
  action:
    - delay: 00:05  # Waits 5 minutes
    - service: homekit.start
    - service: logbook.log
      data_template:
        name: HomeKit
        message: has started
