- action:
  - service: mqtt.publish
    data:
      topic: flic/black
      payload: "{{ trigger.to_state.attributes.click_type }}"
  alias: Black Flic - Single
  trigger:
  - platform: event
    event_type: flic_click
    event_data:
      button_name: flic_80e4da720d43
      click_type: single

- action:
  - service: mqtt.publish
    data:
      topic: flic/black
      payload: "double"
  alias: Black Flic - Double
  trigger:
  - platform: event
    event_type: flic_click
    event_data:
      button_name: flic_80e4da720d43
      click_type: double

- action:
  - service: mqtt.publish
    data:
      topic: flic/black
      payload: "hold"
  alias: Black Flic - Hold
  trigger:
  - platform: event
    event_type: flic_click
    event_data:
      button_name: flic_80e4da720d43
      click_type: hold

- action:
  - service: logger.set_level
    data_template:
      homeassistant.components: "{{ trigger.to_state.state }}"
  alias: Log Level
  trigger:
  - platform: state
    entity_id: input_select.log_level

- action:
  - service: shell_command.checkout_dev_branch_from_github
    data:
      branch: "{{ trigger.to_state.state }}"
  - service: shell_command.update_new_commits_sensor
    data:
      api_password: !secret http_password
  alias: Checkout GIT Dev Branch
  trigger:
  - platform: state
    entity_id: input_select.git_branch
    to: dev

- action:
  - service: shell_command.checkout_master_branch_from_github
    data:
      branch: "{{ trigger.to_state.state }}"
  - service: shell_command.update_new_commits_sensor
    data:
      api_password: !secret http_password
  alias: Checkout GIT Master Branch
  trigger:
  - platform: state
    entity_id: input_select.git_branch
    to: master

- action:
  - service: shell_command.update_new_commits_sensor
    data:
      api_password: !secret http_password
  alias: 'Get Branch and Commits info'
  trigger:
    platform: homeassistant
    event: start
