
####################################################
#                      Home                        #
####################################################

#home:
default_view:
  view: yes
  icon: mdi:castle
  entities:
    - camera.front_door
    - camera.storagecam
    - sensor.kitchen_temperature
    - sensor.hallway_temperature
    - weather.dark_sky
    - media_player.livingroom
    - media_player.davys_echo_dot
    - media_player.davys_echo
    - media_player.davy_s_reverb_ai
    # - device_tracker.iphone_van_isabel
    # - device_tracker.davy_bayesian
    - group.itunes
    - group.light_groups
    - group.automation
    # - group.weather_overview
    # - group.daily_forecast
    # - group.ring_doorbell
    - group.shortcuts

automation:
  name: Automation
  control: hidden
  entities:
    - switch.sunlight_scening
    - switch.auto_fluxer
    - input_select.destination
    - sensor.me_to_destination

date and time:
  name: Date & Time
  view: no
  entities:
    - sensor.date
    - sensor.time
    # - sensor.claire_time
    # - sensor.mum_time

####################################################
#                   Downstairs                     #
####################################################

downstairs:
  name: Downstairs
  icon: mdi:sofa
  view: yes
  entities:
    - group.tv
    - group.lights
    # - media_player.itunes
    - group.all_scenes
    - group.available_switches
    - group.hue_motion_sensors
    # - group.hue_temperature_sensors
    # - group.hue_lux_sensors

downstairs_lights:
  name: Downstairs Lights
  view: no
  control: hidden
  entities:
    - light.hue_desk
    - light.hue_lightstrip
    - light.hue_livingroom
    - light.tv_lights
    - light.fibaro_kitchen_level
    - light.fibaro_table_level
    - light.fibaro_table2_level
    - light.fibaro_table3_level
    - light.fibaro_hallway_level

available_switches:
  name: Switches
  view: no
  control: hidden
  entities:
    - switch.livingroom_lights
    - switch.dinner_lights
    - switch.goodnight
    - switch.kitchen_lights
    - switch.table_lights
    - switch.tv
    # - automation.downstairs_lights_dim

tv:
  name: TV Scenes
  view: no
  control: hidden
  entities:
    # - script.1521695976118
    # - script.1521694771100
    # - script.1521696758169
    # - switch.tvpower
    # - light.gateway_light_7811dcfd812f
    # - light.gateway_light_7811dce13ad6
    # - scene.story_time
    # - scene.livingroom_bright
    # - light.hall_bulb
    - switch.goodnight


all_scenes:
  name: All Scenes
  view: no
  control: hidden
  entities:
    # - scene.all_lights_on
    # - scene.desk_off
    # - scene.desk_on
    # - scene.dinner_off
    # - scene.dinner_on
    # - scene.kitchen_off
    # - scene.kitchen_on
    # - scene.livingroom_off
    # - scene.livingroom_on
    # - scene.movie_paused
    # - scene.movie_resumed
    # - scene.night_light
    # - scene.table_off
    # - scene.table_on
    - scene.downstairs_night
    - scene.downstairs_evening
    - scene.downstairs_daylight
    - scene.table_evening
    - scene.table_daylight
    - scene.table_night
    - scene.livingroom_evening
    - scene.livingroom_daylight
    - scene.livingroom_night

####################################################
#                    History Graphs                #
####################################################

graphs:
  name: History Graphs
  icon: mdi:history
  view: yes
  entities:
    - group.internet_graph
    - group.power_graph
    - group.lights_graph
    - group.temperature_graph
    # - group.model_s_graph

battery_graph:
  view: no
  entities:
    - history_graph.battery_use

internet_graph:
  view: no
  entities:
    - history_graph.internet_graph

power_graph:
  view: no
  entities:
    - history_graph.power_consumption_graph

lights_graph:
  view: no
  entities:
    - history_graph.lights_usage_graph

temperature_graph:
  view: no
  entities:
    - history_graph.temperature_graph

# model_s_graph:
#   view: no
#   entities:
#     - history_graph.car_stats

####################################################
#                  System Status                   #
####################################################

system status:
  name: System Status
  icon: mdi:settings
  view: yes
  entities:
    - group.date_and_time
    - group.firmware
    - group.git
    - group.internet
    - group.core_network
    - group.core_devices
    - group.ha_devices
    - group.media_devices
    - group.rpi_resources
    - group.zwave
    # - group.emergency
    - group.flic
    - group.speech_engine
    - input_select.log_level
    - group.people
    - group.sun

shortcuts:
  name: Shortcuts
  view: no
  entities:
    - weblink.router
    - weblink.grafana
    - weblink.nodered

emergency:
  name: Emergency
  view: no
  control: hidden
  entities:
    - switch.wemo_bedroom

zwave:
  name: Z-Wave
  view: no
  entities:
    - zwave.aeotec_zw090_zstick_gen5_eu
    - zwave.fibaro_hallway
    - zwave.fibaro_kitchen
    - zwave.fibaro_stair
    - zwave.fibaro_table
    - zwave.fibaro_smoke_sensor

####################################################
#                                                  #
#                     Garden                       #
#                                                  #
####################################################

# garden:
#   view: yes
#   icon: mdi:flower
#   entities:
#     - group.bougainvillea
#     - group.chilli
#     - group.citrus
#     - group.herb
#     - group.maple
#     - group.mertyl
#     - group.jasmine
#     - group.strawberry
#     - group.top_bed
#     - group.veggie_patch
