####################################################
#               Certificate Expiry                 #
####################################################

- platform: cert_expiry
  host: dglerum.noip.me

- platform: uptime
  unit_of_measurement: days
