#################################################################
#                                                               #
#                      Packages/Firmware                        #
#                                                               #
#################################################################

#################################################################
#                          Customize                            #
#################################################################

homeassistant:
  customize:
    binary_sensor.ha_update_available:
      icon: mdi:cloud-download
    sensor.latest_ha_version:
      icon: mdi:home-assistant
    sensor.ha_installed_version:
      icon: mdi:home-assistant

#################################################################
#                           Group                               #
#################################################################

group:
  firmware:
    name: Firmware Status
    view: no
    entities:
      - sensor.latest_ha_version
      - sensor.ha_installed_version
      - binary_sensor.ha_update_available
      - sensor.ssl_certificate_expiry

#################################################################
#                            HA Update                          #
#################################################################

sensor:
## Check Latest HA Version
  - platform: scrape
    resource: https://www.home-assistant.io
    name: Latest HA Version
    select: ".current-version h1"
    value_template: '{{ value.split(":")[1] }}'

## Check HA Version Installed
  - platform: command_line
    name: 'HA Installed Version'
    command: "cat /data/config/.HA_VERSION"

binary_sensor:
  - platform: template
    sensors:
      ha_update_available:
        value_template: >-
          {{ states.sensor.latest_ha_version.state != states.sensor.ha_installed_version.state and states.sensor.latest_ha_version.state != 'unavailable' }}
        friendly_name: HA Update Available

automation:
## Notify of New HA Update Available
  - alias: HA Update Available Notification
    trigger:
      platform: state
      entity_id: binary_sensor.ha_update_available
      to: 'on'
    action:
      - service: notify.pushover
        data:
          message: 'New Update Available for HA'
          data:
            url: https://www.home-assistant.io
